### LOCAL - Get all contacts
GET http://localhost:3000/contacts

### LOCAL - Get single contact
GET http://localhost:3000/contacts/6aa8c1f21ec02cdfa0a25e45


### RENDER - Get all contacts
GET https://cse341-contacts-17v9.onrender.com/contacts

### RENDER - Get single contact
GET https://cse341-contacts-17v9.onrender.com/contacts/6a9ba30f457d2cdb7475d4c4

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Fernanda",
  "lastName": "Loreno",
  "email": "fernanda.loreno@example.com",
  "favoriteColor": "Pink",
  "birthday": "1965-03-15"
}

### Update a contact
PUT http://localhost:3000/contacts/6aa8c3c09ab3247ce67db657
Content-Type: application/json

{
  "firstName": "Fernanda",
  "lastName": "Loreno",
  "email": "fernanda.loreno@byu.com",
  "favoriteColor": "Green",
  "birthday": "1965-03-15"
}

### Delete a contact
DELETE http://localhost:3000/contacts/6aa8c3c09ab3247ce67db657

